import { Party, PartyGraph } from './models/party.model';

export const MOCK_PARTIES: Party[] = [
  // === CME MARKET CHAIN ===
  {
    id: 'p001',
    name: 'CME Market',
    crdsCode: '??',
    lei: '??',
    partyType: 'Market',
    status: 'ACTIVE',
    legalForm: 'Exchange',
    countryCode: 'US',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'CME_MARKET',
    effectiveFrom: '2020-01-01',
    roles: [{ roleType: 'Market', status: 'ACTIVE', regulatoryJurisdiction: 'US' }],
    accounts: [],
  },
  {
    id: 'p002',
    name: 'CME Clearing',
    crdsCode: '??',
    lei: '??',
    partyType: 'CCP',
    status: 'ACTIVE',
    legalForm: 'Clearing House',
    countryCode: 'US',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'CME_CLEARING',
    effectiveFrom: '2020-01-01',
    roles: [{ roleType: 'CCP', status: 'ACTIVE', regulatoryJurisdiction: 'US' }],
    accounts: [],
  },
  {
    id: 'p003',
    name: 'EUREX Market',
    crdsCode: '??',
    lei: '??',
    partyType: 'Market',
    status: 'ACTIVE',
    legalForm: 'Exchange',
    countryCode: 'DE',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'EUREX_MARKET',
    effectiveFrom: '2020-01-01',
    roles: [{ roleType: 'Market', status: 'ACTIVE', regulatoryJurisdiction: 'EU' }],
    accounts: [],
  },
  {
    id: 'p004',
    name: 'EUREX Clearing',
    crdsCode: '??',
    lei: '??',
    partyType: 'CCP',
    status: 'ACTIVE',
    legalForm: 'Clearing House',
    countryCode: 'DE',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'EUREX_CLEARING',
    effectiveFrom: '2020-01-01',
    roles: [{ roleType: 'CCP', status: 'ACTIVE', regulatoryJurisdiction: 'EU' }],
    accounts: [],
  },
  {
    id: 'p005',
    name: 'BNPP SEC Corp',
    crdsCode: 'BEDUPAR',
    lei: '',
    partyType: 'Firm',
    status: 'ACTIVE',
    legalForm: 'Corporation',
    countryCode: 'US',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'BNPP_SEC_CORP',
    effectiveFrom: '2020-01-01',
    roles: [
      { roleType: 'Booking Firm', status: 'ACTIVE', regulatoryJurisdiction: 'US' },
      { roleType: 'Clearing Member', status: 'ACTIVE', regulatoryJurisdiction: 'US' },
    ],
    accounts: [
      { accountCode: 'JVXIND', accountType: 'Client', currency: 'USD', status: 'ACTIVE' },
    ],
  },
  {
    id: 'p006',
    name: 'BNPP SA Paris',
    crdsCode: 'BEDUPAR',
    lei: 'R0MUWSFPU8MPR08K5P83',
    partyType: 'Firm',
    status: 'ACTIVE',
    legalForm: 'SA',
    countryCode: 'FR',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'BNPP_SA_PARIS',
    effectiveFrom: '2020-01-01',
    roles: [
      { roleType: 'Clearing Member', status: 'ACTIVE', regulatoryJurisdiction: 'EU' },
      { roleType: 'Booking Firm', status: 'ACTIVE', regulatoryJurisdiction: 'EU' },
    ],
    accounts: [
      { accountCode: 'IXOEUR', accountType: 'Firm', currency: 'EUR', status: 'ACTIVE' },
    ],
  },
  {
    id: 'p007',
    name: 'BNPP FM',
    crdsCode: 'BNABPAR',
    lei: '6EWKUOFGVX5DQJHFGT48',
    partyType: 'Client',
    status: 'ACTIVE',
    legalForm: 'Fund Manager',
    countryCode: 'FR',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'BNPP_FM',
    effectiveFrom: '2020-01-01',
    roles: [
      { roleType: 'Client', status: 'ACTIVE', regulatoryJurisdiction: 'EU' },
      { roleType: 'Executing Broker', status: 'ACTIVE', regulatoryJurisdiction: 'EU' },
    ],
    accounts: [
      { accountCode: 'JVXIND', accountType: 'Client', currency: 'USD', status: 'ACTIVE' },
      { accountCode: 'IXOEUR', accountType: 'Client', currency: 'EUR', status: 'ACTIVE' },
      { accountCode: 'SOCFRA', accountType: 'Client', currency: 'EUR', status: 'ACTIVE' },
    ],
  },
  // === CFL SIMPLE CLIENT CHAIN ===
  {
    id: 'p008',
    name: 'BNPP SA London',
    crdsCode: 'PARBLON',
    lei: 'R0MUWSFPU8MPR08K5P83',
    partyType: 'Firm',
    status: 'ACTIVE',
    legalForm: 'Branch',
    countryCode: 'GB',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'BNPP_SA_LONDON',
    effectiveFrom: '2020-01-01',
    roles: [
      { roleType: 'Clearing Member', status: 'ACTIVE', regulatoryJurisdiction: 'UK' },
      { roleType: 'Booking Firm', status: 'ACTIVE', regulatoryJurisdiction: 'UK' },
    ],
    accounts: [
      { accountCode: 'B627U15', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
      { accountCode: 'B627U17', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
      { accountCode: 'B627U09', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
    ],
  },
  {
    id: 'p009',
    name: 'AAML U',
    crdsCode: 'AMMMLON',
    lei: '5493000QM2EOMFY1G222',
    partyType: 'Client',
    status: 'ACTIVE',
    legalForm: 'Asset Manager',
    countryCode: 'GB',
    sourceSystem: 'MOCK',
    sourceIdentifier: 'AAML_U',
    effectiveFrom: '2020-01-01',
    roles: [
      { roleType: 'Client', status: 'ACTIVE', regulatoryJurisdiction: 'UK' },
    ],
    accounts: [
      { accountCode: 'B627U15', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
      { accountCode: 'B627U17', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
      { accountCode: 'B627U09', accountType: 'Client', currency: 'GBP', status: 'ACTIVE' },
    ],
  },
];

// ── Graph definitions ──────────────────────────────────────────────────

export const MOCK_GRAPHS: PartyGraph[] = [
  {
    id: 'graph-fm-arbitrage',
    title: 'FM (ex Arbitrage) – EUREX & CME',
    partyIds: ['p001','p002','p003','p004','p005','p006','p007'],
    nodes: [
      { id: 'p001', label: 'CME Market',      role: 'Market',           tier: 'market',  x: 60,  y: 60  },
      { id: 'p002', label: 'CME Clearing',    role: 'CCP',              tier: 'market',  x: 280, y: 60  },
      { id: 'p003', label: 'EUREX Clearing',  role: 'CCP',              tier: 'market',  x: 560, y: 60  },
      { id: 'p004', label: 'EUREX Market',    role: 'Market',           tier: 'market',  x: 780, y: 60  },
      { id: 'p005', label: 'BNPP SEC Corp',   role: 'Booking Firm / Clearing Member', tier: 'firm', x: 200, y: 260 },
      { id: 'p006', label: 'BNPP SA Paris',   role: 'Clearing Member / Booking Firm', tier: 'firm', x: 500, y: 260 },
      { id: 'p007', label: 'BNPP FM',         role: 'Client / Executing Broker',      tier: 'client', x: 350, y: 440 },
    ],
    edges: [
      { id: 'e1', from: 'p002', to: 'p001', label: 'Clears',       type: 'clears' },
      { id: 'e2', from: 'p003', to: 'p004', label: 'Clears',       type: 'clears' },
      { id: 'e3', from: 'p005', to: 'p002', label: 'Clears',       type: 'clears' },
      { id: 'e4', from: 'p006', to: 'p003', label: 'Clears',       type: 'clears' },
      { id: 'e5', from: 'p005', to: 'p006', label: 'Is member of', type: 'member' },
      { id: 'e6', from: 'p007', to: 'p005', label: 'Clears (Agreement)', type: 'agreement' },
      { id: 'e7', from: 'p007', to: 'p006', label: 'Clears (Agreement)', type: 'agreement' },
    ],
  },
  {
    id: 'graph-cfl-simple',
    title: 'Simple Client – CFL Use Case',
    partyIds: ['p008','p009'],
    nodes: [
      { id: 'p008', label: 'BNPP SA London', role: 'Clearing Member / Booking Firm', tier: 'firm',   x: 300, y: 60  },
      { id: 'p009', label: 'AAML U',         role: 'Client',                          tier: 'client', x: 300, y: 260 },
    ],
    edges: [
      { id: 'e1', from: 'p008', to: 'p009', label: 'Clears (Agreement)', type: 'agreement' },
    ],
  },
];
